Add Setup Guides
DIT112-V21/group-09 pull request #104
Opened 2021-05-12 19:11 UTC by ramadi-a

Add Setup Guides for Windows and MacOS

- Add Introduction
- Add Install SMCE
- Add Install SmartRover frontend app
- Add Get Arduino sketch file
- Add Install MQTT

Resolves #33

2021-05-12 19:38 UTC, axe007 requested changes
Color scheme is good. 

If this was only for the "Setup guides", then it is fine.

But we need to add subnav for Manual control page, Mission map, mission setup, mission table, user registration and login, settings page. It will be a copy of the wiki page, but within the Frontend app. 

But my main concern is if someone is reading this "Help page", then they have already installed the Frontend app. Main purpose of the Help page for the Frontend app, is explain everything only within "Frontend app".

2021-05-15 15:44 UTC, axe007 requested changes
## Changes requested:
1. SmartRover project. Just a welcome text "copying" some project introduction and features part from the Readme and Wiki pages.  And just mention how to use Help pages. That's all.
2. Settings - How to do settings. Especially mention settings where user needs to take a look before starting to use the Frontend app.
3. Registration and user login. Suggest to the user that it is better to register and login before starting to do anything with the Mission.
4. Manual control. Just explain everything in one page, so that all parts of the page are relevant to each other.
5. Mission control. 
6. Troubleshooting. Frequently asked questions & answers if users run into some problems.

And we need to remove top tabs that are currently "Manual control", "Mission control".

2021-05-17 22:31 UTC, ramadi-a commented
Update help page
- Add the six mentioned points above
-  Change color scheme

Next:

- Add the rest of the instructions.
- Add terminal commands list

Resolves #33  #104

2021-05-17 22:59 UTC, axe007 approved these changes
Layout is good. And we will work on the content as we update the Wiki pages. Thanks.

2021-05-17 22:59 UTC, merged