Implement basic obstacle avoidance
DIT112-V21/group-09 pull request #14
Opened 2021-04-07 17:44 UTC by axe007

## Updated implementation for obstacle avoidance.

### Basic features:
* Uses enum for car's driving modes.
* SmartCar start off with random speed (40-60), angle (-45 to 0) and distance (100-150 meters) to randomize start of the each drive.
* Slows down when UltraSonic sensor detects anything within 2.5 meters in front.
* Slowly approach the object, start avoiding when within 2 meters.
* Car takes ultrasonic measurement and swerves to left for 1.5 seconds, then takes 2nd measurement.
* Car "tries" to guess the angle of approach based on those 2 measurements and will try either left or right move to "clear" the object. This logic still needs more testing and refinement.
* Reverse backwards until there is something detected in back IR sensor with 50 centimeters.
* "Tries" to avoid wall to the left or right depending on additional left or right sensors.
* If car is "drive" mode, but speed is too low, the car tries to unstuck itself by reversing a bit and going forward slow again.

### Further improvements planned:
* Need to research gyroscope capabilities. Drive to preset heading and "resume" same heading after obstacle avoiding manoeuvre.

Implements to #13

2021-04-07 17:51 UTC, ramadi-a approved these changes
Well done

2021-04-07 17:52 UTC, platisd requested changes

2021-04-07 17:52 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +    }
You should look into enum classes and not use strings :grin:

2021-04-07 17:52 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +        if (car.getSpeed() >= 0 && car.getSpeed() < 0.025 && (currentMode == "explore" || currentMode == "slow" || currentMode == "reverse")) {
The two calls to `getSpeed()` can potentially return different values which in turn can potentially be the source of a nasty and hard to find bug.

Same elsewhere.

2021-04-07 17:52 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +    if ((frontUS.getDistance() > 0 && frontUS.getDistance() < 300) || (frontUS.getDistance() > 0 && frontUS.getDistance() < 100 && frontIR.getDistance() < 40)) {
You are calling `getDistance` multiple times which means that you are conducting multiple **different** measurements.

What would happen for example if on the first call you get `500` and in the second call you get `0` (which is a valid scenario btw, especially in the real world where measurements are noisy)?

Same elsewhere.

2021-04-07 17:57 UTC, axe007 commented on arduino/smartcar/smartcar.ino
> +    }
Sure. This is first naive try at C++. Initially also tried to use switch case, but apparently C++ string handling is totally different. Didn't research much until I got things sort of "working".

2021-04-07 17:59 UTC, axe007 commented on arduino/smartcar/smartcar.ino
> +        if (car.getSpeed() >= 0 && car.getSpeed() < 0.025 && (currentMode == "explore" || currentMode == "slow" || currentMode == "reverse")) {
Noted. I'm still not so happy with separate moving and monitoring methods. Very messy for my liking. Just started off like that and stuck with it for now. Will improve as I learn more.

2021-04-07 18:00 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +    }
No reason to apologize. With `enum` you can use `switch-case` statements.

2021-04-07 18:13 UTC, axe007 commented
@ramadi-a @OneMoreOreo @kam56 @nikalc Hey guys. When you get a chance, please take this sketch out for a drive.

Let me know of your suggestions or if you notice something illogical.
Please note that unstuckBack is buggy. Just reset car to spawn position or recompile.

Thanks a lot.

2021-04-07 18:19 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +    if ((frontUS.getDistance() > 0 && frontUS.getDistance() < 300) || (frontUS.getDistance() > 0 && frontUS.getDistance() < 100 && frontIR.getDistance() < 40)) {
Don't forget this comment @axe007, it's the most important one! :+1:

2021-04-10 16:06 UTC, platisd approved these changes
It looks like it'd work so it's approved. There are several things that could be improved so I left some comments.

2021-04-10 16:06 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +    }
Should these be separate if's or one if and many else if's?

2021-04-10 16:06 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +String reportMode() {
Pro tip: You could potentially use a `std::map<DrivingMode, String>` instead of this entire function.

2021-04-10 16:06 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +        break;
Pro tip: This can be replaced by `return frontUS.getDistance();`

2021-04-10 16:09 UTC, axe007 commented on arduino/smartcar/smartcar.ino
> +    }
I tried doing these as one if and else if. It seemed to be only triggering one of the measuring and ignore all others. 

Maybe that time I was doing it wrong. Still needs more testing and refinements.

2021-04-10 16:11 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +    }
Yeah, that's how an `else if` should work. If you intend to always check all the conditions then it looks like it should.

2021-04-10 16:17 UTC, merged