Improve Frontend App
DIT112-V21/group-09 pull request #23
Opened 2021-04-14 01:47 UTC by kam56

## Current features
* The background picture, logo, and some other features are added.
* A layout is prepared so that it shall be used as a template for the rest of the pages.

 ## Future Improvements

* The navigation menu on the manual control page is not responsive to the size of the window. But we will fix it while working on the relative user story.
* I tried to make the Header on the manual control page to be sticky to the top while scrolling. But, it needs some javascript. So, that is on our to-do list.

Fixes #2

2021-04-14 16:01 UTC, axe007 requested changes
Let's work more on the following items:
- Main and child containers to optimize their width and ratio.
- Menu control
- Footer section height and adjustment
- Create template pages for all section.

I will update you all tomorrow. Thanks.

2021-04-15 20:04 UTC, axe007 approved these changes

2021-04-16 07:19 UTC, nikalc reviewed
Great job!

2021-04-16 15:20 UTC, OneMoreOreo approved these changes
Frontend App updates approved.

Adds very good looking updates.

2021-04-16 16:09 UTC, merged