Mission builder table layout
DIT112-V21/group-09 pull request #62
Opened 2021-04-25 01:30 UTC by ramadi-a

Implement mission builder table layout

- Add one row by default that includes (heading, speed and distance)
- User can add more steps (rows) by click
- User can remove steps (rows) by checkbox and click

Resolves #61

2021-04-25 01:32 UTC, ramadi-a commented
The table breaks the page layout in small screens, we can solve that issue later

2021-04-25 10:09 UTC, axe007 requested changes
Overall, very good job. 

Please "fix" the parts I left as code review. Let's discuss if we need to. 

Thanks.

2021-04-25 10:09 UTC, axe007 commented on frontendApp/mission.html
> +							</TR>
Here is my observation:
- Please make all tags to be lowercase.
- Header row tag is <th> not <tr1>
- Please look into CSS definition for the table and column width. You can define it only for the TH row, and it just applies to other rows. When I delete all the rows, you can see header row is compressed and table has no width at all.
- On line 145, Distance data row is missing a line break and appearing behind Speed data row.
- We need to add max property to Heading and Speed. Heading is between 0 to 360.
- Speed is not exactly the speed. As we discussed with Jacob, it is percentage of the motor output, which is between 0 to 100.
- Heading and distance needs min="0" property at zero. If I decrease, all goes to negative numbers. "Speed" could be negative (down to -100) which is going reverse.
- If I delete a row from the middle, the row numbering loose track and if I add one more row, then last 2 rows are numbered same. Not sure how to fix, but it is something we need to sort out.

2021-04-25 10:09 UTC, axe007 commented on frontendApp/mission.html
> +		<script>
Please put the JS into a js file in assets folder, so that our html & css "presentation" is separate from mission business logic. Also that way it could be easier to send mission info to db and over mqtt.

2021-04-25 10:10 UTC, axe007 commented on frontendApp/mission.html
> +		<script>
Maybe down here, when you delete a row you might be able "reset" row numbering.

2021-04-28 14:23 UTC, ramadi-a commented on frontendApp/mission.html
> +							</TR>
Renumbering steps upon deleting a row not fixed. I was experimenting with it but could not solve it.

2021-04-28 19:58 UTC, axe007 requested changes

2021-04-28 19:58 UTC, axe007 commented on frontendApp/mission.html
> +				element4.name = "txtbox[]";
Max and Min constraints work as expected on 1st row.

But you're not adding those properties here, so any subsequent rows added do not have those max, min stuff. 

Also I suggest to rename element1, element2 into names that better represent stuff for that columns. Would make your code more readable. At the moment, I have no idea like what "element2" means.

Thanks.

2021-04-28 19:59 UTC, axe007 commented on frontendApp/mission.html
> +							</TR>
No worries, we can solve that problem somehow.

2021-04-28 21:51 UTC, axe007 approved these changes
Works good. Thanks.

2021-04-28 21:51 UTC, merged